#
# +++++++++++++++++++++++++++++++++++++++++++++++++
# Setting up the image
# +++++++++++++++++++++++++++++++++++++++++++++++++
#

FROM php:7.1-fpm

MAINTAINER Rico B.

#
# +++++++++++++++++++++++++++++++++++++++++++++++++
# Software install
# +++++++++++++++++++++++++++++++++++++++++++++++++
# Installing tools and PHP extensions using "apt", "docker-php", "pecl"

# Install "curl", "libmemcached-dev", "libpq-dev", "libjpeg-dev",
# "libpng-dev", "libfreetype6-dev", "libssl-dev", "libmcrypt-dev",
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    curl \
    libmemcached-dev \
    libz-dev \
    libpq-dev \
    libjpeg-dev \
    libpng-dev \
    libfreetype6-dev \
    libssl-dev \
    libmcrypt-dev \
  && rm -rf /var/lib/apt/lists/*

# Install the PHP mcrypt extention
RUN docker-php-ext-install mcrypt \
  # Install the PHP pdo_mysql extention
  && docker-php-ext-install pdo_mysql \
  # Install the PHP pdo_pgsql extention
  && docker-php-ext-install pdo_pgsql \
  # Install the PHP gd library
  && docker-php-ext-configure gd \
    --enable-gd-native-ttf \
    --with-jpeg-dir=/usr/lib \
    --with-freetype-dir=/usr/include/freetype2 && \
    docker-php-ext-install gd
